version: '3'
services: 
  song_db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: flask_api
      POSTGRES_USER: 'postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  song_service:
    depends_on:
      - song_db
    image: song_service
    build: 
      context: ./songService
    env_file:
      - ./songService/.env
    expose:
      - "5000"
    volumes:
      - static_volume:/songService/static
  user_db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: user_db
      POSTGRES_USER: 'postgres'
    volumes:
      - postgres-userdb-data:/var/lib/postgresql/data
  user_service:
    depends_on:
      - user_db
    image: user_service
    build: 
      context: ./userService
    env_file:
      - ./userService/.env
    expose:
      - "5000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./apigateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/songService/static
    depends_on: 
      - song_service
      - user_service
  frontend:
    image: frontend
    restart: always
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.10.0-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP Management UI
      - '15672:15672'

volumes:
  postgres-data:
  postgres-userdb-data:
  static_volume: