version: '3'
services: 
  song_db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: flask_api
      POSTGRES_USER: 'postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
  song_service:
    depends_on:
      - song_db
    image: song_service
    build: 
      context: ./songService
    env_file:
      - ./songService/.env
    expose:
      - "5000"
    volumes:
      - static_volume:/songService/static
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./apigateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/songService/static
    depends_on: 
      - song_service
  frontend:
    image: frontend
    restart: always
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres-data:
  static_volume: