apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  defaultBackend:
    service:
      name: default-http-backend
      port: 
        number: 80
  rules:
  - host: myminikube.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port: 
              number: 8080
  - host: microservices.all
    http:
      paths:
      - path: /api/songs
        pathType: Prefix
        backend:
          service:
            name: song-service
            port: 
              number: 80
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port: 
              number: 80