apiVersion : apps/v1
kind: Deployment
metadata:
  name: niekvalphenvirtuoso 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: niekvalphenvirtuoso
  template:
    metadata:
      labels:
        app: niekvalphenvirtuoso 
    spec:
      containers:
        - name: niekvalphenvirtuoso 
          image: virtuosoregistery.azurecr.io/niekvalphenvirtuoso
          ports:
          - containerPort: 80