"""empty message

Revision ID: d879970d3b16
Revises: ee8267e9697c
Create Date: 2022-05-08 14:58:12.275096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd879970d3b16'
down_revision = 'ee8267e9697c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('songs', sa.Column('artist', sa.String(length=255), nullable=True))
    op.add_column('songs', sa.Column('audio_file', sa.String(length=255), nullable=True))
    op.add_column('songs', sa.Column('genre', sa.String(length=255), nullable=True))
    op.drop_column('songs', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('songs', 'genre')
    op.drop_column('songs', 'audio_file')
    op.drop_column('songs', 'artist')
    op.drop_column('songs', 'title')
    # ### end Alembic commands ###
