apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 4
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: niekvalphen/userapici:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000