apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: LoadBalancer
  selector:
    app: user
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    type: restapi
spec:
  selector: 
    matchLabels:
      app: user
  replicas: 3
  template:
    metadata:
      name: user
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: niekvalphen/userapici:latest
          ports:
            - containerPort: 5000