name: Docker Image CI playlistService

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: playlistService

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PLAYLISTAPI_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./playlistService
          file: ./playlistService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/playlistapici:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
